language: node_js

node_js:
  - 10.8

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - cd example && npm install
  - cd ..

script:
  - npm run test
