version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    target_branch: 'main'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'
